import Navbar from '../components/common/Navbar';
import { Link } from 'react-router-dom';

export default function PrivacyPolicy() {
  return (
    <div className="min-h-screen bg-cream flex flex-col overflow-x-hidden">
      <Navbar />
      
      <div className="flex-grow max-w-4xl mx-auto px-6 py-12 md:py-20 w-full">
        <div className="retro-box bg-white p-8 md:p-12 mb-12">
          <h1 className="text-4xl md:text-5xl font-bangers text-ink mb-6">Privacy Policy</h1>
          <p className="font-mono text-sm text-ink/70 mb-8 border-b-2 border-ink/10 pb-6">Last updated: March 31, 2026</p>
          
          <div className="prose prose-lg font-grotesk text-ink max-w-none prose-headings:font-bangers prose-headings:text-ink prose-a:text-orange hover:prose-a:text-red transition-colors prose-strong:font-bold prose-strong:text-ink">
            
            <p className="lead text-xl text-ink/80 mb-6">
              This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
            </p>
            
            <p className="mb-8">
              We use Your Personal Data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. This Privacy Policy has been created with the help of the <a href="https://www.termsfeed.com/privacy-policy-generator/" target="_blank" rel="noopener noreferrer" className="font-bold underline decoration-2 underline-offset-4">TermsFeed Privacy Policy Generator</a>.
            </p>

            <h2 className="text-3xl mt-12 mb-6 text-pink">Interpretation and Definitions</h2>
            
            <h3 className="text-2xl mt-8 mb-4">Interpretation</h3>
            <p className="mb-6">
              The words whose initial letters are capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
            </p>

            <h3 className="text-2xl mt-8 mb-4">Definitions</h3>
            <p className="mb-4">For the purposes of this Privacy Policy:</p>
            <ul className="list-disc pl-6 space-y-4 mb-8">
              <li>
                <strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.
              </li>
              <li>
                <strong>Affiliate</strong> means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.
              </li>
              <li>
                <strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to <strong>Restroon</strong>.
              </li>
              <li>
                <strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.
              </li>
              <li>
                <strong>Country</strong> refers to: India
              </li>
              <li>
                <strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.
              </li>
              <li>
                <strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.
              </li>
              <li>
                <strong>Service</strong> refers to the Website and Application.
              </li>
              <li>
                <strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.
              </li>
              <li>
                <strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).
              </li>
              <li>
                <strong>Website</strong> refers to Restroon.
              </li>
              <li>
                <strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.
              </li>
            </ul>

            <h2 className="text-3xl mt-12 mb-6 text-pink">Collecting and Using Your Personal Data</h2>
            
            <h3 className="text-2xl mt-8 mb-4">Types of Data Collected</h3>
            
            <h4 className="text-xl font-bold mt-6 mb-3">Personal Data</h4>
            <p className="mb-4">
              While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
            </p>
            <ul className="list-disc pl-6 space-y-2 mb-6">
              <li>Email address</li>
              <li>First name and last name</li>
              <li>Phone number</li>
              <li>Address, State, Province, ZIP/Postal code, City</li>
              <li>Usage Data</li>
            </ul>

            <h4 className="text-xl font-bold mt-6 mb-3">Usage Data</h4>
            <p className="mb-4">Usage Data is collected automatically when using the Service.</p>
            <p className="mb-6">
              Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
            </p>

            <h2 className="text-3xl mt-12 mb-6 text-pink">Contact Us</h2>
            <p className="mb-4">If you have any questions about this Privacy Policy, You can contact us:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li>By email: support@restroon.com</li>
            </ul>
          </div>
        </div>
      </div>
      
      {/* Footer */}
      <footer className="bg-ink border-t-3 border-yellow py-8 mt-auto">
        <div className="max-w-7xl mx-auto px-6 flex flex-col md:flex-row items-center justify-between gap-4">
          <div className="flex items-center gap-3">
            <span className="text-2xl">🛵</span>
            <span className="font-bangers text-2xl text-yellow tracking-wider">RESTROON</span>
          </div>
          <p className="font-mono text-sm text-cream/50">
            © 2026 Restroon. Built with ❤️ for local cafes.
          </p>
          <div className="flex gap-6">
            <Link to="/privacy" className="font-grotesk text-sm text-cream/60 hover:text-yellow transition-colors">Privacy</Link>
            <a href="#" className="font-grotesk text-sm text-cream/60 hover:text-yellow transition-colors">Terms</a>
            <a href="#" className="font-grotesk text-sm text-cream/60 hover:text-yellow transition-colors">Contact</a>
          </div>
        </div>
      </footer>
    </div>
  );
}
